/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppToursRouteImport } from './routes/_app.tours'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppReservationsRouteImport } from './routes/_app.reservations'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppLogisticsRouteImport } from './routes/_app.logistics'
import { Route as AppHotelsRouteImport } from './routes/_app.hotels'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCustomersRouteImport } from './routes/_app.customers'
import { Route as AppCalendarRouteImport } from './routes/_app.calendar'
import { Route as AppReservationsNewRouteImport } from './routes/_app.reservations.new'
import { Route as AppReservationsIdRouteImport } from './routes/_app.reservations.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppToursRoute = AppToursRouteImport.update({
  id: '/tours',
  path: '/tours',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReservationsRoute = AppReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppLogisticsRoute = AppLogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => AppRoute,
} as any)
const AppHotelsRoute = AppHotelsRouteImport.update({
  id: '/hotels',
  path: '/hotels',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppReservationsNewRoute = AppReservationsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppReservationsRoute,
} as any)
const AppReservationsIdRoute = AppReservationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppReservationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/calendar': typeof AppCalendarRoute
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/hotels': typeof AppHotelsRoute
  '/logistics': typeof AppLogisticsRoute
  '/reports': typeof AppReportsRoute
  '/reservations': typeof AppReservationsRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/tours': typeof AppToursRoute
  '/users': typeof AppUsersRoute
  '/reservations/$id': typeof AppReservationsIdRoute
  '/reservations/new': typeof AppReservationsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/calendar': typeof AppCalendarRoute
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/hotels': typeof AppHotelsRoute
  '/logistics': typeof AppLogisticsRoute
  '/reports': typeof AppReportsRoute
  '/reservations': typeof AppReservationsRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/tours': typeof AppToursRoute
  '/users': typeof AppUsersRoute
  '/reservations/$id': typeof AppReservationsIdRoute
  '/reservations/new': typeof AppReservationsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/customers': typeof AppCustomersRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/hotels': typeof AppHotelsRoute
  '/_app/logistics': typeof AppLogisticsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/reservations': typeof AppReservationsRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/_app/tours': typeof AppToursRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/reservations/$id': typeof AppReservationsIdRoute
  '/_app/reservations/new': typeof AppReservationsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/calendar'
    | '/customers'
    | '/dashboard'
    | '/hotels'
    | '/logistics'
    | '/reports'
    | '/reservations'
    | '/settings'
    | '/tours'
    | '/users'
    | '/reservations/$id'
    | '/reservations/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/calendar'
    | '/customers'
    | '/dashboard'
    | '/hotels'
    | '/logistics'
    | '/reports'
    | '/reservations'
    | '/settings'
    | '/tours'
    | '/users'
    | '/reservations/$id'
    | '/reservations/new'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/calendar'
    | '/_app/customers'
    | '/_app/dashboard'
    | '/_app/hotels'
    | '/_app/logistics'
    | '/_app/reports'
    | '/_app/reservations'
    | '/_app/settings'
    | '/_app/tours'
    | '/_app/users'
    | '/_app/reservations/$id'
    | '/_app/reservations/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tours': {
      id: '/_app/tours'
      path: '/tours'
      fullPath: '/tours'
      preLoaderRoute: typeof AppToursRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reservations': {
      id: '/_app/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof AppReservationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/logistics': {
      id: '/_app/logistics'
      path: '/logistics'
      fullPath: '/logistics'
      preLoaderRoute: typeof AppLogisticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hotels': {
      id: '/_app/hotels'
      path: '/hotels'
      fullPath: '/hotels'
      preLoaderRoute: typeof AppHotelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reservations/new': {
      id: '/_app/reservations/new'
      path: '/new'
      fullPath: '/reservations/new'
      preLoaderRoute: typeof AppReservationsNewRouteImport
      parentRoute: typeof AppReservationsRoute
    }
    '/_app/reservations/$id': {
      id: '/_app/reservations/$id'
      path: '/$id'
      fullPath: '/reservations/$id'
      preLoaderRoute: typeof AppReservationsIdRouteImport
      parentRoute: typeof AppReservationsRoute
    }
  }
}

interface AppReservationsRouteChildren {
  AppReservationsIdRoute: typeof AppReservationsIdRoute
  AppReservationsNewRoute: typeof AppReservationsNewRoute
}

const AppReservationsRouteChildren: AppReservationsRouteChildren = {
  AppReservationsIdRoute: AppReservationsIdRoute,
  AppReservationsNewRoute: AppReservationsNewRoute,
}

const AppReservationsRouteWithChildren = AppReservationsRoute._addFileChildren(
  AppReservationsRouteChildren,
)

interface AppRouteChildren {
  AppCalendarRoute: typeof AppCalendarRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppHotelsRoute: typeof AppHotelsRoute
  AppLogisticsRoute: typeof AppLogisticsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppReservationsRoute: typeof AppReservationsRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppToursRoute: typeof AppToursRoute
  AppUsersRoute: typeof AppUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCalendarRoute: AppCalendarRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppHotelsRoute: AppHotelsRoute,
  AppLogisticsRoute: AppLogisticsRoute,
  AppReportsRoute: AppReportsRoute,
  AppReservationsRoute: AppReservationsRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppToursRoute: AppToursRoute,
  AppUsersRoute: AppUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
